In [17]:
import numpy as np

In [18]:
a=np.array([1,2,3,4,5])#Creating a numpy array using list
print(a)

[1 2 3 4 5]


In [19]:
print(np.__version__)#The version of numpy is stored under this variable

1.26.4


In [20]:
print(type(a))#Type of numpy array

<class 'numpy.ndarray'>


In [21]:
a=np.array((1,2,3,4,5))#Creating using a tuple
print(a)

[1 2 3 4 5]


In [22]:
#0 dimension,1 dimension,2 dimension,3 dimension nparrays
a=np.array(1)
print(a.ndim)

0


In [23]:
a=np.array([1,2])
print(a.ndim)

1


In [24]:
a=np.array([[1,2],[3,4]])
print(a.ndim)

2


In [25]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.ndim)

3


In [26]:
#Creating higher dimensional array with ndmin attribute in array method
a=np.array([1,2,3,4],ndmin=6)
print(a,a.ndim)

[[[[[[1 2 3 4]]]]]] 6
